export { default as Events } from './events-components/Events.jsx'
export { default as Infos } from './infos-components/Infos.jsx'
export { default as News } from './news-components/News.jsx'
export { default as Hero } from './hero-components/Hero.jsx'
export { default as ImageSlider } from './image-slider-components/ImageSlider.jsx'
